### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by AB10110F** [huy-hng/anyline.nvim#4]
When I install the plugin and open neovim, it immediately shows me this error:
![image](https://github.com/huy-hng/anyline.nvim/assets/57847167/7d49b3a6-4bf3-4eaa-b26f-52639b59d03c)
---
Once inside the code, indentation char is shown like this until I move inside the block:
![image](https://github.com/huy-hng/anyline.nvim/assets/57847167/27288069-d833-4589-941c-912cb91b74ec)
---
I'm using neovim 0.9.4 on windows 10

I really liked your plugin, and I would use it despite the unexpected behavior, but it throws that error every time I try to type on insert mode :(

**Comment by huy-hng** [comment]
Sorry for the late response! For some reason I didn't get a notification for this issue.
This should be fixed, I'm confused as to why this has worked for anyone ever 😂

The weird slanted indent lines happens because the font you are using doesn't have an italic version, which causes the font engine to 'force' slant the indent symbol.
The reason it is being slanted in the first place is because I've linked the highlight to `Comment` instead of creating one.
I have no idea why I did it this way, but I've linked it to `NonText` for now which usually isn't italic.

Let me know if you have any other issues :)
